### ISSUE TITLE
Which parts of the destination service aren't working?

### ISSUE THREAD

**Issue by kioplato** [giuseppeamato/lsc-scim-plugin#1]
In README.md, there is a part that says "The destination service is still experimental, although mostly working."

I would like to know what functionality is missing. I'm having some trouble with modifying some entries.

EDIT: Update/modify should be working. Here is the related [function](https://github.com/giuseppeamato/lsc-scim-plugin/blob/031250825b372fc269674c687cf958d6774c2650/src/main/java/it/pz8/lsc/plugins/connectors/scim/ScimDao.java#L317).
However, what functionality is missing from destination service?

**Comment by giuseppeamato** [comment]
Hi, I'll explain briefly, let's assume we have a user with the following attributes:

```
{
	"schemas": [],
	"name": {
		"givenName": "Giuseppe",
		"familyName": "Amato"		
	},
	"userName": "g.amato",
	"password": "password",
	"emails": [{
		"primary": true,
		"value": "g@gmail.com",
		"type": "home"
	},
	{
		"value": "g.amato@work.com",
		"type": "work"
	}],
	"addresses": [{
		"type": "work",
		"formatted": "100 Universal City Plaza Hollywood, CA 91608 USA"
	},
	{
		"type": "home",
		"formatted": "456 Hollywood Blvd\nHollywood, CA 91608 USA"
	}]
}
```
when you execute the following SCIM operation on some versions of WSO2 Identity Server :

```
{
  "schemas": ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
  "Operations":[
   {
     "op":"remove",
     "path": "emails[type eq work]"
    }
  ]
 }
```

as a result, in addition to the work email, both the addresses are also deleted. This is clearly a behavior that has nothing to do with LSC and its SCIM plugin, I'm only concerned about the generation of a compliant SCIM resource by the plugin, and in my opionion this is implemented correctly, but I thought it useful to give a notice.
